insert into hotelinfo (name, address) values ('Radisson', 'Bangalore')
insert into hotelinfo (name, address) values ('Taj','Hosur')
insert into hotelinfo (name, address) values ('Bino', 'Tumkur')
insert into hotelinfo (name, address) values ('Sara Sara', 'Airport')
insert into hotelinfo (name, address) values ('Boater', 'Mejestic')
insert into hotelinfo (name, address) values ('Grand', 'Bangalore')
insert into hotelinfo (name, address) values ('ibis', 'Bangalore')
insert into hotelinfo (name, address) values ('Southpool', 'Bangalore')
insert into hotelinfo (name, address) values ('Tent', 'Bangalore')
insert into hotelinfo (name, address) values ('Riverside', 'Bangalore')
insert into hotelinfo (name, address) values ('Holiday In', 'Bangalore')
insert into hotelinfo (name, address) values ('Avenue', 'Bangalore')
insert into hotelinfo (name, address) values ('Hotel 7', 'Bangalore')
